title: Quan Nguyen Hien # your name (or website title) here
logo: "/images/avatar.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently a senior at The College of Wooster majoring in Statistical Data Sciences and Mathematics with a minor in Economics
  <br><br>
  I have a strong interest in Data Science as well as Applied Machine Learning & Deep Learning, especially in financial industry or business intelligence.
  <br><br>
  <a href="https://www.linkedin.com/in/quan-nguyen-hien/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
